### ISSUE TITLE
Feature update request

### ISSUE THREAD

**Issue by Cosplayeridol** [lewangdev/autotranslate#12]
In addition, can the translation function of gpt4 be supported? Many new models have been added to the openai official website. Can they be added?

**Comment by lewangdev** [comment]
GPT-4 added at 1dcfc4c94fa9e6c4026ea8f1a63509775b547438.

By the way, you can input any model here :

<img width="688" alt="image" src="https://github.com/lewangdev/autotranslate/assets/1455685/0b609a65-28fa-473b-8b14-eaa0340fe34b">
