### ISSUE TITLE
运行时出现错误显示：RuntimeError:Library libcublas.so.11 is not found or cannot be loaded

### ISSUE THREAD

**Issue by ads233** [lewangdev/autotranslate#13]
在Run the model这一步时出现的问题如下：![2](https://github.com/lewangdev/autotranslate/assets/153071412/d2873d85-dde0-4159-b675-9c2ab22d6381)

**Comment by lewangdev** [comment]
fixed at https://github.com/lewangdev/autotranslate/commit/52fe9da28ac93ceff65a33f0ed4696f77b404326

The original library's filename was changed by the author 2 hours ago.
