### ISSUE TITLE
日文字幕translate之後還是日文

### ISSUE THREAD

**Issue by b940315** [lewangdev/autotranslate#15]
請問是否我哪邊設定有問題呢?
![image](https://github.com/lewangdev/autotranslate/assets/55653865/441bf1ee-30cd-42d9-ae70-02faa7e29f6f)

**Comment by lewangdev** [comment]
谢谢反馈。这周比较忙，可能要等到周末的时候才有时间解决这个问题

**Comment by b940315** [comment]
您好，Install libraries的步驟有跳出錯誤

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
llmx 0.0.15a0 requires cohere, which is not installed.
llmx 0.0.15a0 requires tiktoken, which is not installed.

**Comment by b940315** [comment]
原因應該是我API的問題，提個小請求，希望translate那邊可以上傳自己準備的字幕檔
