### ISSUE TITLE
[BUG]There seems to be a problem with Import libraries for Python

### ISSUE THREAD

**Issue by Cosplayeridol** [lewangdev/autotranslate#16]
![image](https://github.com/lewangdev/autotranslate/assets/85826393/615714f4-4d7c-4556-b627-7e0c9f3c8a6b)
![image](https://github.com/lewangdev/autotranslate/assets/85826393/46d4440d-2369-4bec-a53e-f98408c0495d)

**Comment by Cosplayeridol** [comment]
The error I see is that the Model selection part is not working properly

**Comment by lewangdev** [comment]
Hi，
 由于 colab 最近的 CUDA 版本更新，运行 faster-whisper 时暂时无法利用GPU(onnxruntime is incompatible with cuda 12.2)，因此会卡在一直'加载模型'的部分
 看到这里请按以下操作：
 - 在上方菜单栏选择'工具(tools)' ——> '命令面板(Command palette)
 - 输入'使用后备运行时版本(use fallback runtime version)'
 - 确认
 - 笔记本会自动重新连接
 - 重新连接完成后，正常按之前的步骤执行后面的单元格即可

这应该只是临时一段时间的问题，等 colab 修复这个不兼容问题就不用这一步了
[解决方法来自于 N46Whisper](https://github.com/Ayanaminn/N46Whisper/commit/bad5a5963ce47d52a9945b55ea26542d17cfd901)
