### ISSUE TITLE
提示错误

### ISSUE THREAD

**Issue by fieri** [lewangdev/autotranslate#4]
UnboundLocalError                         Traceback (most recent call last)
[<ipython-input-16-c11d336b9f3c>](https://localhost:8080/#) in <cell line: 101>()
     99   return fragments_translated
    100 
--> 101 fragments_translated = translate_fragments(new_fragments, count_of_sentence_send_once_limit)
    102 
    103 # Save translation as json file

1 frames
[<ipython-input-16-c11d336b9f3c>](https://localhost:8080/#) in translate_by_chatgpt(sentences, max_retry_times, deployment_id, model_name, temperature)
     73       print(f"==Tranlate Retry with {current_retry_times} times")
     74       continue
---> 75   return sentences_translated
     76 
     77 def translate_fragments(fragments, sentence_send_limit=5):

UnboundLocalError: local variable 'sentences_translated' referenced before assignment

**Comment by lewangdev** [comment]
Fixed in PR https://github.com/lewangdev/autotranslate/pull/5
