### ISSUE TITLE
How to get model to run on all files when given Google Drive folder path?

### ISSUE THREAD

**Issue by pikaOne1138** [lewangdev/autotranslate#6]
I input the folder path of Google Drive, and it also printed out that 64 files were selected. But when I "Run the model", it only runs the last file. How can I adjust or modify this?

**Comment by lewangdev** [comment]
I will fix this bug the next day.

**Comment by lewangdev** [comment]
I am busy today. After reviewing my code, I found that my colab does not support multiple files. However, I made some slight modifications to the code for your reference, enabling it to automatically handle multiple files. It is placed in this branch. I haven't had time to test it yet.  

https://github.com/lewangdev/autotranslate/tree/feat/support-multifiles-in-google-drive

You can read and test in colab:

[![notebook shield](https://img.shields.io/static/v1?label=&message=Notebook&color=blue&style=for-the-badge&logo=googlecolab&link=https://colab.research.google.com/github/lewangdev/autotranslate/blob/feat/support-multifiles-in-google-drive/autotranslate.ipynb)](https://colab.research.google.com/github/lewangdev/autotranslate/blob/feat/support-multifiles-in-google-drive/autotranslate.ipynb)

**Comment by pikaOne1138** [comment]
I used it today, and it reported an error the first time. I found that there should be no other folders in the target folder, or there will be problems.
After that, it ran smoothly, but I put in almost 50 files. I finished the transcripts for the files.
I then proceeded to translate them, but after translating two files, Colab was interrupted due to inactivity.

I have a small suggestion. Is it possible to split out part of this project so that it can directly read the SRTs in the folder and translate them?

-- The above English was translated from Chinese using Bard.

**Comment by lewangdev** [comment]
The srt subtitle file is a different format that cannot be processed by this colab project. The program's logic is to convert the video into audio and then recognize it as an intermediate state of segments, so it is unable to separate out the logic for handling srt separately.
