### ISSUE TITLE
希望对日语优化~ 大家转录、翻译日语的时候是什么设置呢

### ISSUE THREAD

**Issue by nb95276** [lewangdev/autotranslate#7]
如题 这个是普遍需求吧~

**Comment by lewangdev** [comment]
日语也是支持的，但是我不会日语，所以没有仔细对比过翻译的效果。请问你遇到什么问题了吗

**Comment by ads233** [comment]
在通过Merge words/segments to sentences后日文文字间的间隔太宽了吧？
![QQ拼音截图20231211161435](https://github.com/lewangdev/autotranslate/assets/153071412/0dfcfb9f-617b-40a8-9b63-22a60a23d2d6)

**Comment by lewangdev** [comment]
选择 ja

<img width="933" alt="image" src="https://github.com/lewangdev/autotranslate/assets/1455685/f463226b-5127-4936-ac36-f5b1f66a76ac">
