### ISSUE TITLE
请求在Model selection添加whisper-large-v3模型，以及修复日文在Merge words/segments to sentences后文字间距过大问题

### ISSUE THREAD

**Issue by ads233** [lewangdev/autotranslate#9]
![QQ拼音截图20231211161435](https://github.com/lewangdev/autotranslate/assets/153071412/70d465a5-0f57-4533-b4e3-e0deb9a06811)
日文文字间的间隔太大了吧，这样看起来难受......
![2](https://github.com/lewangdev/autotranslate/assets/153071412/d58ac49c-8066-4b4a-9eaa-771e47073eb7)

**Comment by ads233** [comment]
作者能参考一下这个日本YouTube的设计吗？他那边不能直接用链接提交给云端硬盘，要我自己上传的话我上传速度蜗牛一样......所以希望作者能把他的设计结合到你这边。https://www.youtube.com/watch?v=B494g8LEx3w

**Comment by lewangdev** [comment]
视频的链接可以发出来，我运行试试
> ![QQ拼音截图20231211161435](https://private-user-images.githubusercontent.com/153071412/289475129-70d465a5-0f57-4533-b4e3-e0deb9a06811.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMDM2MzAsIm5iZiI6MTcwMjMwMzMzMCwicGF0aCI6Ii8xNTMwNzE0MTIvMjg5NDc1MTI5LTcwZDQ2NWE1LTBmNTctNDUzMy1iNGUzLWUwZGViOWEwNjgxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQxNDAyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZWNhODc4NDkzMzkzYjI0YTEzNTEwODYwOTc5MzNiNTI0M2QyMWE1ZWU2ZDAxYjRiMDhkZWFhNzJkZWZlNTMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xorn2W9ThFSnL4JrW894u-R5zlw4G7dQjx8UCxrKjQg) 日文文字间的间隔太大了吧，这样看起来难受...... ![2](https://private-user-images.githubusercontent.com/153071412/289476992-d58ac49c-8066-4b4a-9eaa-771e47073eb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMDM2MzAsIm5iZiI6MTcwMjMwMzMzMCwicGF0aCI6Ii8xNTMwNzE0MTIvMjg5NDc2OTkyLWQ1OGFjNDljLTgwNjYtNGI0YS05ZWFhLTc3MWU0NzA3M2ViNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQxNDAyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODBhY2MxMmVjYTQ3NWY0ZGE1NDQ1ZWZkN2NjMmQ2N2U3MjA1Y2EyMmFiNTlkNmYxYmZlNTI0ZGU3MmZmNzhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rDi9Up5GkZf04D9CQrsstlT81HJ-T_UwvwKdTW-zy8M)

**Comment by ads233** [comment]
https://www.youtube.com/watch?v=pkPUZ8N7rbQ&t=2s

**Comment by lewangdev** [comment]
<img width="981" alt="image" src="https://github.com/lewangdev/autotranslate/assets/1455685/ebfaebc2-c185-42ea-af58-c49cccc2eaba">

> https://www.youtube.com/watch?v=pkPUZ8N7rbQ&t=2s

**Comment by ads233** [comment]
出字幕的时候正常
![2](https://github.com/lewangdev/autotranslate/assets/153071412/5c642e11-57e8-48c7-a40e-9fe4612cb75f)
可是经过Merge words/segments to sentences这之后就乱了QAQ
![3](https://github.com/lewangdev/autotranslate/assets/153071412/30ec9759-c80a-4b93-8692-fa9bc7c43436)

**Comment by ads233** [comment]
我运用你的设计和那位日本人设计的样本都有用Potplayer测试播放，用日本那位楼主的设计没有字幕乱排的问题......

**Comment by lewangdev** [comment]
fixed

<img width="715" alt="image" src="https://github.com/lewangdev/autotranslate/assets/1455685/ccb7062b-13ca-40b6-83ee-e906fc9de26e">
